services:
  app_dev:
    container_name: imposter_game_dev
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && node server.js"
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
